spring.application.name=api-blank
spring.datasource.url=${DATABASE_URL:jdbc:postgresql://localhost:5432/webii_tp2}
spring.datasource.username=${POSTGRES_USER:webii_tp2}
spring.datasource.password=${POSTGRES_PASSWORD:webii_tp2}
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
dummyjson.base-url=${DUMMYJSON_BASE_URL:https://dummyjson.com}
dummyjson.connect-timeout=3s
dummyjson.read-timeout=5s
springdoc.override-with-generic-response=false
